name: koueki
version: 1.38β
description: 交易の交易のための交易プラグイン
author: seiya0818
website: seiya0818.jimdo.com/
depend: [Vault]
softdepend: [Vault]

main: jp.seiya0818.Koueki
database: false

commands:
  koueki:
    description: 交易プラグイン系統のコマンド
    usage: |
           /<command> start - 交易を開始します。
           /<command> quit - 交易を終了します。
           /<command> start (player) - 交易を開始させます。
           /<command> quit (player) - 交易を終了させます。
    permission-message: 権限がありません。

permissions:
  koueki.admin:
    description: 交易プラグインの運営権限
    children:
      koueki.sign: true
      koueki.start.others: true
      koueki.quit.others: true
      koueki.create: true
      koueki.delete: true
      koueki.setname: true
      koueki.list: true
      koueki.info: true
      koueki.reload: true
      koueki.Adminhelp: true
    default: op
  koueki.start:
    description: 交易モードに設定する権限を与えます。
    default: true
  koueki.stop:
    description: 交易モードを強制終了する権限を与えます。
    default: op
  koueki.quit:
    description: 交易モードを終了する権限を与えます。
    default: op
  koueki.help:
    description: ヘルプを表示します。
    default: true
  koueki.sign:
    description: 看板を作成します。
    default: op
  koueki.start.others:
    description: 交易モードに設定させる権限を与えます。
    default: op
  koueki.quit.others:
    description: 交易モードを終了させる権限を与えます。
    default: op
  koueki.create:
    description: 交易品を作成します。
    default: op
  koueki.delete:
    description: 交易品を削除します。
    default: op
  koueki.list:
    description: 交易品一覧を表示します。
    default: op
  koueki.info:
    description: 交易品の情報を表示します。
    default: op
  koueki.reload:
    description: 交易品をリロードします。
    default: op
  koueki.adminhelp:
    description: 運営用の交易ヘルプを表示します。
    default: op
